#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <vector>

// Tiny JPEGs generated with ImageMagick/libjpeg from explicit solid colors and
// an asymmetric red/blue split. Base64 keeps the encoded fixtures reviewable
// and lets tests pass decoded bytes directly to RasterForge without filesystem
// access or a test-time encoder.
namespace jpeg_fixtures {

inline constexpr std::string_view rgb444_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/"
    "2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/"
    "2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/"
    "wAARCAABAAIDAREA"
    "AhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACv/EABQQAQAAAAAAAAAAAAAAAAAAAAD/"
    "xAAUAQEA"
    "AAAAAAAAAAAAAAAAAAAG/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AEecB7/"
    "/Z"};

inline constexpr std::string_view gray_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/"
    "2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAALCAABAAIBAREA/"
    "8QAFAABAAAAAAAA"
    "AAAAAAAAAAAAAP/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AP//Z"};

inline constexpr std::string_view progressive_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/"
    "2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/"
    "2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/"
    "wgARCAACAAIDAREA"
    "AhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABUBAQEAAAAAAAAAAAAAAAAAAAcI/"
    "9oADAMB"
    "AAIQAxAAAAE96UK//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABBQJ//"
    "8QAFBEBAAAAAAAA"
    "AAAAAAAAAAAAAP/aAAgBAwEBPwF//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwF//"
    "8QA"
    "FBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQAGPwJ//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/"
    "aAAgB"
    "AQABPyF//9oADAMBAAIAAwAAABAf/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPxB//"
    "8QA"
    "FBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPxB//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/"
    "aAAgB"
    "AQABPxB//9k="};

inline constexpr std::string_view progressive_budget_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/"
    "2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcU"
    "FhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/"
    "2wBDAQcHBwoIChMKChMoGhYaKCgoKCgo"
    "KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/"
    "wgARCAEAAQADAREA"
    "AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAWAQEBAQAAAAAAAAAAAAAAAAAABAX/"
    "2gAM"
    "AwEAAhADEAAAAZPVjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/"
    "/E"
    "ABQQAQAAAAAAAAAAAAAAAAAAAKD/2gAIAQEAAQUCAB//xAAUEQEAAAAAAAAAAAAAAAAAAACg/"
    "9oA"
    "CAEDAQE/AQAf/8QAFBEBAAAAAAAAAAAAAAAAAAAAoP/aAAgBAgEBPwEAH//"
    "EABQQAQAAAAAAAAAA"
    "AAAAAAAAAKD/2gAIAQEABj8CAB//xAAUEAEAAAAAAAAAAAAAAAAAAACg/9oACAEBAAE/IQAf/"
    "9oA"
    "DAMBAAIAAwAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/"
    "xAAU"
    "EQEAAAAAAAAAAAAAAAAAAACg/9oACAEDAQE/EAAf/8QAFBEBAAAAAAAAAAAAAAAAAAAAoP/"
    "aAAgB"
    "AgEBPxAAH//EABQQAQAAAAAAAAAAAAAAAAAAAKD/2gAIAQEAAT8QAB//2Q=="};

inline constexpr std::string_view sub422_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/"
    "2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYF"
    "BgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/"
    "2wBDAQICAgICAgUDAwUKBwYHCgoKCgoK"
    "CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/"
    "wAARCAAIAAgDASEA"
    "AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAYEAACAwAAAAAAAAAAAAAAAAAACEWEw/"
    "/E"
    "ABUBAQEAAAAAAAAAAAAAAAAAAAcJ/8QAGhEAAAcAAAAAAAAAAAAAAAAAAAQFCDiEtP/"
    "aAAwDAQAC"
    "EQMRAD8Ami1UDaxBVJksYkC1tMhAd9IlbrZC4//Z"};

inline constexpr std::string_view sub420_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/"
    "2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYF"
    "BgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/"
    "2wBDAQICAgICAgUDAwUKBwYHCgoKCgoK"
    "CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/"
    "wAARCAAIAAgDASIA"
    "AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAYEAEAAwEAAAAAAAAAAAAAAAAACEWEw/"
    "/E"
    "ABUBAQEAAAAAAAAAAAAAAAAAAAcJ/8QAGhEAAAcAAAAAAAAAAAAAAAAAAAQFCDiEtP/"
    "aAAwDAQAC"
    "EQMRAD8AmjKqh1cQFUmSxiQLW0yEB30iVutkLj//2Q=="};

inline constexpr std::string_view cmyk_base64{
    "/9j/4AAQSkZJRgABAQAAAAAAAAD/7gAOQWRvYmUAZAAAAAAC/9sAQwABAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB/"
    "9sAQwEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ"
    "EB"
    "AQEB/8AAFAgAAQABBAERAAIRAQMRAQQRAP/EABUAAQEAAAAAAAAAAAAAAAAAAAkK/"
    "8QAFBABAAAA"
    "AAAAAAAAAAAAAAAAAP/EABUBAQEAAAAAAAAAAAAAAAAAAAkK/"
    "8QAFBEBAAAAAAAAAAAAAAAAAAAA"
    "AP/aAA4EAQACEQMRBAAAPwAXxTr+F/D/2Q=="};

[[nodiscard]] inline auto decode_base64(std::string_view encoded)
    -> std::vector<std::uint8_t> {
  constexpr std::string_view alphabet{
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"};
  std::array<std::uint8_t, 256> values{};
  values.fill(0xFF);
  for (std::size_t index = 0; index < alphabet.size(); ++index) {
    values[static_cast<unsigned char>(alphabet[index])] =
        static_cast<std::uint8_t>(index);
  }

  std::vector<std::uint8_t> decoded;
  decoded.reserve((encoded.size() / 4U) * 3U);
  std::uint32_t accumulator{};
  int bits{};
  for (const char character : encoded) {
    if (character == '=') {
      break;
    }
    const auto value = values[static_cast<unsigned char>(character)];
    if (value == 0xFF) {
      continue;
    }
    accumulator = (accumulator << 6U) | value;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      decoded.push_back(static_cast<std::uint8_t>(accumulator >>
                                                  static_cast<unsigned>(bits)));
      accumulator &= (std::uint32_t{1} << static_cast<unsigned>(bits)) - 1U;
    }
  }
  return decoded;
}

} // namespace jpeg_fixtures
